# Generated by Django 5.2.1 on 2025-05-29 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_deleted_cliente_deleted_at'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('AV', 'À vista'), ('FN', 'Financiamento'), ('PR', 'Parcelado')], default='AV', max_length=2)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo')),
            ],
        ),
    ]
