# Generated by Django 5.2.1 on 2025-05-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_deleted_veiculo_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='preco_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço de Compra'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='preco_venda_sugerido',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço de Venda Sugerido'),
        ),
    ]
